name: Node.js CI/CD with Azure VM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Clean previous files on VM
      run: |
        echo "${{ secrets.AETHA_VM_PRIVATE_KEY }}" > aetha_vm_key.pem
        chmod 600 aetha_vm_key.pem
        ssh -o StrictHostKeyChecking=no -i aetha_vm_key.pem aetha_admin@40.117.74.134 "rm -rf ~/aetha-frontend"

    - name: Clone repository on VM
      env:
        AETHA_BACKEND_PAT: ${{ secrets.AETHA_BACKEND_PAT }}
      run: |
        ssh -o StrictHostKeyChecking=no -i aetha_vm_key.pem aetha_admin@40.117.74.134 "git clone https://${AETHA_BACKEND_PAT}@github.com/Project-AETHA/aetha-frontend.git"

    - name: Build and run application on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i aetha_vm_key.pem aetha_admin@40.117.74.134 << 'EOF'
          cd ~/aetha-frontend
          npm install
          nohup npm run dev > app.log 2>&1 &
        EOF
